### ISSUE TITLE
Shabbat times are off

### ISSUE THREAD

**Issue by alBronko** [py-libhdate/py-libhdate#106]
# Observed behavior
Shabbat times are consistently off by about (but not exactly) 20 minutes.

# Expected behavior
Shabbat times would be exact.
29.10.2022
ד' חשוון ה'תשפ"ג
שבת פרשת נח
ירושלים
כניסה: 17:13
יציאה: 18:31
from : https://www.gov.il/apps/dat/shabattimes/

# Steps to reproduce
>>> >import hdate
>>> >import datetime
>>> >z = hdate.Zmanim(date=datetime.date(2022, 10, 28), hebrew=True) #no location because it is Jerusalem by default
>>> >z.candle_lighting
OUTPUT:
datetime.datetime(2022, 10, 28, 17, 35, tzinfo=<DstTzInfo 'Asia/Jerusalem' IDT+3:00:00 DST>)
>>> >z = hdate.Zmanim(date=datetime.date(2022, 10, 29), hebrew=True)
>>> >z.havdalah
OUTPUT:
datetime.datetime(2022, 10, 29, 18, 30, tzinfo=<DstTzInfo 'Asia/Jerusalem' IDT+3:00:00 DST>)

another example:
25.02.2023
ד' אדר ה'תשפ"ג
שבת פרשת תרומה
ירושלים
כניסה: 16:53
יציאה: 18:09
>>> z = hdate.Zmanim(date=datetime.date(2023, 2, 24), hebrew=True)
>>> z.candle_lighting
OUTPUT:
datetime.datetime(2023, 2, 24, 17, 15, tzinfo=<DstTzInfo 'Asia/Jerusalem' IST+2:00:00 STD>)
>>> z = hdate.Zmanim(date=datetime.date(2023, 2, 25), hebrew=True)
>>> z.havdalah
OUTPUT:
datetime.datetime(2023, 2, 25, 18, 10, tzinfo=<DstTzInfo 'Asia/Jerusalem' IST+2:00:00 STD>)

Thank you for your upkeep @tsvi.

**Comment by tsvi** [comment]
Hi @alBronko, thank you for reporting this issue.
It looks like this is due to the fact that I'm using the wrong method to localize the timezone. This issue creeps up time ad again due to the weird JMT timezone that existed 100 years ago. For reference:
- https://bugs.launchpad.net/pytz/+bug/1284592
- https://answers.launchpad.net/pytz/+faq/1

**Comment by alBronko** [comment]
thanks for the quick response. 
I need a little help getting me across the edge. I've tried:
z = hdate.Zmanim(date=datetime.date(2022, 10, 28), hebrew=True)
z.candle_lighting +(z.candle_lighting - z.candle_lighting.replace(tzinfo=pytz.timezone('Asia/Jerusalem')))

also tried
datetime.fromtimestamp(datetime.timestamp(z.candle_lighting.replace(tzinfo=pytz.timezone('Asia/Jerusalem'))))

but that changes the time by 39 minutes (21 minutes minus an hour as can be seen here:
>>> z.candle_lighting.replace(tzinfo=pytz.timezone('Asia/Jerusalem'))
datetime.datetime(2022, 10, 28, 17, 35, tzinfo=<DstTzInfo 'Asia/Jerusalem' LMT+2:21:00 STD>)
>>> z.candle_lighting
datetime.datetime(2022, 10, 28, 17, 35, tzinfo=<DstTzInfo 'Asia/Jerusalem' IDT+3:00:00 DST>)

on the other hand in the other example:
>>> z.candle_lighting.replace(tzinfo=pytz.timezone('Asia/Jerusalem'))
datetime.datetime(2023, 2, 24, 17, 15, tzinfo=<DstTzInfo 'Asia/Jerusalem' LMT+2:21:00 STD>)
>>> z.candle_lighting
datetime.datetime(2023, 2, 24, 17, 15, tzinfo=<DstTzInfo 'Asia/Jerusalem' IST+2:00:00 STD>)

I have a feeling it has to do with DST, but my programming skills aren't up fo the challenge.
Help please?

**Comment by tsvi** [comment]
Ok, I managed to figure out the issue, it is not a bug.
You're looking at the candle-lighting times in Jerusalem. Unlike most of the world, the minhag in Jerusalem is to have an offset of 40 minutes before sunset. So you need to change the candle_lighthing_offset to 40.

```python
>>> z = hdate.Zmanim(date=datetime(2022, 10, 28), candle_lighting_offset=40)
>>> z.candle_lighting
datetime.datetime(2022, 10, 28, 17, 15, tzinfo=<DstTzInfo 'Asia/Jerusalem' IDT+3:00:00 DST>)
```

The above code still gives a time that's 2 minutes off due to some rounding errors. But it's not as bad as I thought.
